# Usa una imagen base de Golang
FROM golang:1.22

# Establecer directorio de trabajo
WORKDIR /app

# Copiar archivos al contenedor
COPY . .

# Descargar dependencias y compilar
RUN go mod tidy
RUN go build -o main .

# Exponer el puerto (ajústalo según tu app)
EXPOSE 8082

# Ejecutar la aplicación
CMD ["/app/main"]
